name: pipeline

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github page
        uses: actions/checkout@v3
        with:
          repository: starburst997/starburst997.github.io
          path: git
          ref: "master"
          lfs: false
          token: ${{ secrets.pat }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            git/resume
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('git/resume') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run test
      - name: Lint
        run: yarn run lint
      - name: Create env file
        run: |
          touch .env
          echo "CI=1" >> .env
          echo "CI_PROJECT_URL='https://github.com/starburst997/nuxt-resume'" >> .env
          echo "CI_COMMIT_SHORT_SHA='$(git rev-parse --short HEAD)'" >> .env
          echo "NODE_ENV='production'" >> .env
      - name: Check outputs env
        run: cat .env
      - name: Static HTML export with Nuxt
        run: |
          yarn run generate
          yarn run strip-scripts
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Generate PDF
        run: ci/generate-pdf.sh
      - name: Remove files
        run: |
          rm -Rf git/resume/_nuxt
          rm git/resume/200.html
          rm git/resume/README.md
      - name: Commit changes
        working-directory: git
        run: |
          git config --global user.name 'Jean-Denis Boivin'
          git config --global user.email 'jd@boiv.in'
          git add resume
          git commit -am "[AUTO] Update Résumé"
          git push
      