name: Deploy resume to github pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 1
      CI_PROJECT_URL: 'https://github.com/starburst997/nuxt-resume'

    steps:
      - name: Add CI_COMMIT_SHORT_SHA env property with commit short sha
        run: echo "CI_COMMIT_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github page
        uses: actions/checkout@v3
        with:
          repository: starburst997/starburst997.github.io
          path: git
          ref: "master"
          lfs: false
          token: ${{ secrets.pat }}
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "::set-output name=manager::yarn"
            echo "::set-output name=command::install"
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "::set-output name=manager::npm"
            echo "::set-output name=command::ci"
            exit 0
          else
            echo "Unable to determine packager manager"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            dist
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Test
        run: ${{ steps.detect-package-manager.outputs.manager }} run test
      - name: Lint
        run: ${{ steps.detect-package-manager.outputs.manager }} run lint
      - name: Static HTML export with Nuxt
        run: |
          ${{ steps.detect-package-manager.outputs.manager }} run generate
          ${{ steps.detect-package-manager.outputs.manager }} run strip-scripts
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Generate PDF
        run: ci/generate-pdf.sh
      
      - name: Commit changes
        working-directory: git
        run: |
          git config --global user.name 'Jean-Denis Boivin'
          git config --global user.email 'jd@boiv.in'
          git add resume
          git commit -am "[AUTO] Update Résumé"
          git push
      